name: widget_tooltip_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/widget_tooltip
  - packages/burst_icon_button
  - packages/floating_widget
  - apps/example

dev_dependencies:
  melos: ^7.0.0

melos:
  repository: https://github.com/hongmono/flutter-packages

  scripts:
    analyze:
      run: dart analyze .
      description: Run dart analyze in all packages.

    test:
      run: cd packages/widget_tooltip && flutter test
      description: Run flutter test for widget_tooltip package.

    format:
      run: dart format .
      description: Format all Dart files.
