name: widget_tooltip_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/widget_tooltip
  - apps/example

dev_dependencies:
  melos: ^7.0.0

melos:
  repository: https://github.com/hongmono/widget_tooltip

  scripts:
    analyze:
      run: dart analyze .
      exec:
        concurrency: 1
      description: Run dart analyze in all packages.

    test:
      run: flutter test
      packageFilters:
        dirExists: test
      description: Run flutter test in all packages.

    format:
      run: dart format .
      description: Format all Dart files.
