name: widget_tooltip
description: "Widget Tooltip is a Flutter package that provides a tooltip widget that can be used to display a tooltip on any widget"
version: 1.2.2
repository: https://github.com/hongmono/widget_tooltip
homepage: https://github.com/hongmono

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0