name: Publish to pub.dev

on:
  push:
    tags:
    - 'widget_tooltip-v*'
    - 'burst_icon_button-v*'
    - 'floating_widget-v*'

jobs:
  determine-package:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.pkg.outputs.package }}
    steps:
      - name: Determine package from tag
        id: pkg
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PACKAGE="${TAG%%-v*}"
          echo "package=$PACKAGE" >> "$GITHUB_OUTPUT"

  publish:
    needs: determine-package
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: packages/${{ needs.determine-package.outputs.package }}
